### PR TITLE
Style update (dev): Improve styling to match newer versions closer

### PR DESCRIPTION
**Pull request by CritLoren**
- Removes corner code since it was creating graphical glitches;
- Made the pinned tabs use flex box so they automatically adjust based on available space, with a minimum width, then they flex grow, as opposed to a fixed column count;
- Lots of tiny tweaks to opacities, widths, and gaps between items to make the sidebar more responsive;
- Some grouping of variables;
- Fixed overflow issues (the entire left panel was vertically scrolling for me, not just the tabs);
- Formatted with Prettier

### CODE REVIEW

**Comment by KiKaraage** [comment]
Can you showed how the sidebar looks on your setup now? I don't really get it, particularly on the lack of padding for the normal tabs (compared to the pinned tabs)

image

**Comment by CritLoren** [comment]
Oh that's interesting, I'm on Mercury myself, rather than mainland firefox, maybe that's the differentiator?:
image
 (ignore the wider sidebar, i increased my panel width to 300 as a tweak that I haven't merged in)

**Comment by CritLoren** [comment]
Is your screenshot from regular firefox? I'd like to test things out on that

**Comment by CritLoren** [comment]
image
no even on regular firefox the side spacing is fine, you sure you replaced all of your user styling for sidebery with mine, and not just added on top or smth?

**Comment by ishid4** [comment]
Hey @CritLoren,
Can you explain a little bit more about the graphical issue of rounded corners? It gives a "vibe" to the sidebar with the overall design.

**Comment by CritLoren** [comment]
hey @ishid4 they were showing up overlapping awkwardly on top of the pinned tabs at the top whenever i'd hover over the sidebar, if  you're willing to spend some time to investigate it further be my guest, i'm guessing they're more relevant when you have the sidebar hidden by default and appear on hover.

**Pull request merged**
